src/Interactive/WebPortal/Models/AwsProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Ica.StackIt.Interactive.WebPortal.Models
{
	public class AwsProfileViewModel
	{
		public AwsProfileViewModel()
		{
			ServerGroups = new List<string>();
			Groups = new List<string>();
		}

		public Guid Id { get; set; }

		[DisplayName("Profile Name")]
		public string Name { get; set; }

		[DisplayName("Account")]
		public string Account { get; set; }

		[DisplayName("Access Key ID")]
		public string AccessKeyId { get; set; }

		[DisplayName("Secret Access Key")]
		public string SecretAccessKey { get; set; }

		[DisplayName("Default VPC ID")]
		public string DefaultVpcId { get; set; }

		[DisplayName("Subnet ID")]
		public string DefaultSubnetId { get; set; }

		[DisplayName("Hosted Zone")]
		public string HostedZone { get; set; }

		[DisplayName("AD Groups")]
		public List<string> Groups { get; set; }

		public List<string> ServerGroups { get; set; }

		[Display(Name = "Detailed Billing S3 Bucket", Description = "The S3 bucket where Amazon deposits detailed billing reports for this AWS profile.")]
		public string DetailedBillingS3Bucket { get; set; }
	}
}

src/Interactive/WebPortal/Controllers/AwsProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using Amazon.Runtime;

using AwsContrib.EnvelopeCrypto;

using Hangfire;

using Ica.StackIt.Application;
using Ica.StackIt.Application.Command;
using Ica.StackIt.AspNet.Identity.Crowd;
using Ica.StackIt.Core;
using Ica.StackIt.Core.Entities;
using Ica.StackIt.Interactive.WebPortal.Models;

namespace Ica.StackIt.Interactive.WebPortal.Controllers
{
	[Authorize]
	[SessionProfile]
	public class AwsProfileController : Controller
	{
		private readonly IRepository<AwsProfile> _profileRepository;
		private readonly IRepository<IPRange> _ipRangeRepository;
		private readonly ICryptoProvider _cryptoProvider;
		private readonly IBackgroundJobClient _backgroundJobClient;
		private readonly IAuthenticatedUserClient _userClient;
		private readonly IAwsClientFactory _awsClientFactory;

		private const string _encryptedMessagePlaceholder = "(Encrypted)";

		public AwsProfileController(
			IRepository<AwsProfile> profileRepository,
			IRepository<IPRange> ipRangeRepository,
			ICryptoProvider cryptoProvider,
			IBackgroundJobClient backgroundJobClient,
			IAuthenticatedUserClient userClient,
			IAwsClientFactory awsClientFactory)
		{
			_profileRepository = profileRepository;
			_ipRangeRepository = ipRangeRepository;
			_cryptoProvider = cryptoProvider;
			_backgroundJobClient = backgroundJobClient;
			_userClient = userClient;
			_awsClientFactory = awsClientFactory;
		}

		// GET: Profile
		public ActionResult Index()
		{
			IEnumerable<AwsProfile> profiles = _profileRepository.FindAll();
			IEnumerable<AwsProfileViewModel> modelCollection = profiles.Select(x =>
				new AwsProfileViewModel
				{
					Id = x.Id,
					Name = x.Name,
					AccessKeyId = x.AccessKeyId,
					SecretAccessKey = _encryptedMessagePlaceholder
				});
			return View(modelCollection);
		}

		// GET: Profile/Details/5
		public ActionResult Details(Guid id)
		{
			AwsProfile profile = _profileRepository.Find(id);

			var viewModel = new AwsProfileViewModel
			{
				Name = profile.Name,
				AccessKeyId = profile.AccessKeyId,
				SecretAccessKey = _encryptedMessagePlaceholder,
				DefaultVpcId = profile.DefaultVpcId,
				DefaultSubnetId = profile.DefaultSubnetId,
				Id = profile.Id,
				Groups = profile.Groups.ToList(),
				HostedZone = profile.HostedZone,
				DetailedBillingS3Bucket = profile.DetailedBillingS3Bucket,
			};

			return View(viewModel);
		}

		// GET: Profile/Create
		public ActionResult Create()
		{
			IEnumerable<string> activeDirectoryGroups = _userClient.GetAllRoles();

			var model = new AwsProfileViewModel {ServerGroups = activeDirectoryGroups.ToList()};
			return View(model);
		}

		// POST: Profile/Create
		[HttpPost]
		public ActionResult Create(AwsProfileViewModel profileViewModel)
		{
			try
			{
				if (ValidateViewModelAgainstExternalSources(profileViewModel, newProfile: true))
				{
					string dataKey;
					string encryptedStrings = _cryptoProvider.Encrypt(
						out dataKey,
						profileViewModel.SecretAccessKey
						);

					var profile = new AwsProfile
					{
						Name = profileViewModel.Name,
						Account = profileViewModel.Account,
						AccessKeyId = profileViewModel.AccessKeyId,
						EncryptedKey = dataKey,
						EncryptedSecretAccessKey = encryptedStrings,
						DefaultVpcId = profileViewModel.DefaultVpcId,
						DefaultSubnetId = profileViewModel.DefaultSubnetId,
						HostedZone = profileViewModel.HostedZone,
						Groups = profileViewModel.Groups,
						DetailedBillingS3Bucket = profileViewModel.DetailedBillingS3Bucket,
					};

					_profileRepository.Add(profile);

					_backgroundJobClient.Enqueue<CreateDefaultSecurityGroup>(x => x.Execute(profile.Id, profileViewModel.DefaultVpcId));
					_backgroundJobClient.Enqueue<CreateIpRange>(x => x.Execute(profile.Id, profileViewModel.DefaultSubnetId));

					return RedirectToAction("Index");
				}
			}
			catch (Exception e)
			{
				// TODO: Just for debugging! Remove this. Don't show this to the user, but log it somewhere for troubleshooting purposes.
				ModelState.AddModelError("", string.Format("There was a problem creating the profile. {0}", e.Message));
			}

			// If we make it this far, something bad happened. Display the error message to the user.
			return View(profileViewModel);
		}

		// GET: Profile/Edit/5
		public ActionResult Edit(Guid id)
		{
			AwsProfile profile = _profileRepository.Find(id);
			IEnumerable<string> activeDirectoryGroups = _userClient.GetAllRoles();

			var viewModel = new AwsProfileViewModel
			{
				Name = profile.Name,
				Account = profile.Account,
				AccessKeyId = profile.AccessKeyId,
				SecretAccessKey = _encryptedMessagePlaceholder,
				DefaultVpcId = profile.DefaultVpcId,
				DefaultSubnetId = profile.DefaultSubnetId,
				Groups = profile.Groups.ToList(),
				ServerGroups = activeDirectoryGroups.ToList(),
				HostedZone = profile.HostedZone,
				DetailedBillingS3Bucket = profile.DetailedBillingS3Bucket,
			};

			return View(viewModel);
		}

		// POST: Profile/Edit/5
		[HttpPost]
		public ActionResult Edit(Guid id, AwsProfileViewModel profileViewModel)
		{
			try
			{
				AwsProfile profile = _profileRepository.Find(id);

				if (profileViewModel.SecretAccessKey == _encryptedMessagePlaceholder)
				{
					profileViewModel.SecretAccessKey = _cryptoProvider.Decrypt(profile.EncryptedKey, profile.EncryptedSecretAccessKey);
				}

				if (ValidateViewModelAgainstExternalSources(profileViewModel, newProfile: false))
				{
					profile.Name = profileViewModel.Name;
					profile.Account = profileViewModel.Account;
					profile.AccessKeyId = profileViewModel.AccessKeyId;
					profile.DefaultVpcId = profileViewModel.DefaultVpcId;
					profile.DefaultSubnetId = profileViewModel.DefaultSubnetId;
					profile.HostedZone = profileViewModel.HostedZone;
					profile.Groups = profileViewModel.Groups.ToList();
					profile.DetailedBillingS3Bucket = profileViewModel.DetailedBillingS3Bucket;

					if (profileViewModel.SecretAccessKey != _encryptedMessagePlaceholder)
					{
						string dataKey;
						string encryptedAccessKey = _cryptoProvider.Encrypt(out dataKey, profileViewModel.SecretAccessKey);
						profile.EncryptedSecretAccessKey = encryptedAccessKey;
						profile.EncryptedKey = dataKey;
					}

					_profileRepository.Update(profile);

					_backgroundJobClient.Enqueue<CreateIpRange>(x => x.Execute(profileViewModel.Id, profileViewModel.DefaultSubnetId));

					return RedirectToAction("Index");
				}
			}
			catch
			{
				// err, todo?
				return View(profileViewModel);
			}

			return View(profileViewModel);
		}

		// GET: Profile/Delete/5
		public ActionResult Delete(Guid id)
		{
			AwsProfile profile = _profileRepository.Find(id);

			var viewModel = new AwsProfileViewModel
			{
				Name = profile.Name,
				AccessKeyId = profile.AccessKeyId,
				Id = profile.Id
			};

			return View(viewModel);
		}

		// POST: Profile/Delete/5
		[HttpPost]
		public ActionResult Delete(AwsProfileViewModel profileViewModel)
		{
			try
			{
				_profileRepository.Delete(profileViewModel.Id);

				var ipRange = _ipRangeRepository.FindAll().Where(x => x.AwsProfileId == profileViewModel.Id);
				foreach (var range in ipRange)
				{
					_ipRangeRepository.Delete(range);
				}

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		/// <summary>
		///     Take a view model (with an account, access key, and secret access key) and do validations.
		///     Specifically, ensure a profile is associated with one account in the db, and
		///     ensure that an the profile actually belongs to the AWS account that the user said it belongs to.
		///     This method will set the model error state for the request appropriately.
		/// </summary>
		/// <param name="profileViewModel"></param>
		/// <param name="newProfile"></param>
		/// <returns></returns>
		private bool ValidateViewModelAgainstExternalSources(AwsProfileViewModel profileViewModel, bool newProfile)
		{
			var valid = true;
			string profileName;
			var isAlreadyAssociated = TryGetAssociatedProfile(profileViewModel.Account, out profileName);
			if ((isAlreadyAssociated && newProfile) || isAlreadyAssociated && profileName != profileViewModel.Name)
			{
				ModelState.AddModelError("", string.Format("The account {0} is already associated with the profile {1}.", profileViewModel.Account, profileName));
				valid = false;
			}
			else if (!ValidateAccountProfileCredentials(profileViewModel.Account, profileViewModel.AccessKeyId, profileViewModel.SecretAccessKey))
			{
				ModelState.AddModelError("", string.Format("The access key {0} does not belong to the account {1}.", profileViewModel.AccessKeyId, profileViewModel.Account));
				valid = false;
			}

			if (!valid)
			{
				profileViewModel.ServerGroups = _userClient.GetAllRoles().ToList();
			}

			return valid;
		}

		private bool TryGetAssociatedProfile(string account, out string profileName)
		{
			var profile = _profileRepository.FindAll().FirstOrDefault(x => x.Account == account);
			if (profile == null)
			{
				profileName = null;
				return false;
			}

			profileName = profile.Name;
			return true;
		}

		private bool ValidateAccountProfileCredentials(string account, string accessKey, string secretKey)
		{
			var client = _awsClientFactory.GetClient(new BasicAWSCredentials(accessKey, secretKey));
			return client.IdentityService.ValidateProfileOwnership(account);
		}
	}
}

src/Interactive/WebPortal/Views/AwsProfile/Create.cshtml
@model Ica.StackIt.Interactive.WebPortal.Models.AwsProfileViewModel

@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "AwsProfile", FormMethod.Post, new {id = "awsprofile-create-form"}))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>AWS Profile</h4>
		<hr />
		@Html.ValidationSummary(true, "", new {@class = "text-danger"})
		<div class="form-group">
			@Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Account, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.AccessKeyId, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.AccessKeyId, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.AccessKeyId, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.SecretAccessKey, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.SecretAccessKey, new {htmlAttributes = new {@class = "form-control", autocomplete = "off"}})
				@Html.ValidationMessageFor(model => model.SecretAccessKey, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DefaultVpcId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.DefaultVpcId, new { htmlAttributes = new { @class = "form-control" }})
				@Html.ValidationMessageFor(model => model.DefaultVpcId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DefaultSubnetId, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.DefaultSubnetId, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.DefaultSubnetId, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.HostedZone, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.HostedZone, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.HostedZone, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DetailedBillingS3Bucket, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.DetailedBillingS3Bucket, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.DetailedBillingS3Bucket, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-2 control-label">
				@Html.LabelFor(model => model.Groups)
			</div>
			<div class="col-md-10">
				<div id="awsprofile-create-groups-wrapper"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input id="awsprofile-create-submit" type="button" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
	<style>
		.ui-autocomplete {
			height: 100px;
			overflow-x: hidden;
			overflow-y: auto;
		}

		.ui-menu .ui-menu-item {
			padding: 0 10px 0 0;
			white-space: nowrap;
		}
	</style>
	<script>
		$(document).ready(function() {
			var groups = @Html.Raw(Json.Encode(Model.ServerGroups));

			var groupsCtrl = new AutoCompleteMultiSelect();

			groupsCtrl.AttachmentId("#awsprofile-create-groups-wrapper");
			groupsCtrl.List(groups);
			groupsCtrl.Setup();

			$("#awsprofile-create-submit").click(function(event) {
				groupsCtrl.ListToHiddenFields();
				$("#awsprofile-create-form").submit();
			});
		});
	</script>
}

src/Interactive/WebPortal/Views/AwsProfile/Delete.cshtml
@model Ica.StackIt.Interactive.WebPortal.Models.AwsProfileViewModel

@{
	ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>Aws Profile</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.AccessKeyId)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.AccessKeyId)
		</dd>

	</dl>

	@using (Html.BeginForm()) {
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Delete" class="btn btn-default" /> |
			@Html.ActionLink("Back to List", "Index")
		</div>
	}
</div>

src/Interactive/WebPortal/Views/AwsProfile/Details.cshtml
@model Ica.StackIt.Interactive.WebPortal.Models.AwsProfileViewModel

@{
	ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
	<h4>Aws Profile</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.AccessKeyId)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.AccessKeyId)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.SecretAccessKey)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.SecretAccessKey)
		</dd>
		
		<dt>
			@Html.DisplayNameFor(model => model.DefaultVpcId)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.DefaultVpcId)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.DefaultSubnetId)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.DefaultSubnetId)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.HostedZone)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.HostedZone)
		</dd>
		
	    <dt>
	        @Html.DisplayNameFor(model => model.DetailedBillingS3Bucket)
	    </dt>
		
	    <dd>
	        @Html.DisplayFor(model => model.DetailedBillingS3Bucket)
	    </dd>

	    <dt>
			@Html.DisplayNameFor(model => model.Groups)
		</dt>

		@foreach (string group in Model.Groups)
		{
			<dd>@group</dd>
		}
	</dl>
</div>
<p>
	@Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
	@Html.ActionLink("Back to List", "Index")
</p>

src/Interactive/WebPortal/Views/AwsProfile/Edit.cshtml
@model Ica.StackIt.Interactive.WebPortal.Models.AwsProfileViewModel

@{
	ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "AwsProfile", FormMethod.Post, new {id = "awsprofile-edit-form"}))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>AwsProfileViewModel</h4>
		<hr />
		@Html.ValidationSummary(true, "", new {@class = "text-danger"})
		@Html.HiddenFor(model => model.Id)

		<div class="form-group">
			@Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Account, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.AccessKeyId, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.AccessKeyId, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.AccessKeyId, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.SecretAccessKey, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.SecretAccessKey, new {htmlAttributes = new {@class = "form-control", autocomplete = "off"}})
				@Html.ValidationMessageFor(model => model.SecretAccessKey, "", new {@class = "text-danger"})
			</div>
		</div>
		
		<div class="form-group">
			@Html.LabelFor(model => model.DefaultVpcId, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.DefaultVpcId, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.DefaultVpcId, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DefaultSubnetId, new {@class = "control-label col-md-2"})
			<div class="col-md-10">
				@Html.EditorFor(model => model.DefaultSubnetId, new {htmlAttributes = new {@class = "form-control"}})
				@Html.ValidationMessageFor(model => model.DefaultSubnetId, "", new {@class = "text-danger"})
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.HostedZone, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.HostedZone, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.HostedZone, "", new { @class = "text-danger" })
			</div>
		</div>
		
		<div class="form-group">
			@Html.LabelFor(model => model.DetailedBillingS3Bucket, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.DetailedBillingS3Bucket, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.DetailedBillingS3Bucket, "", new { @class = "text-danger" })
			</div>
		</div>

	    <div class="form-group">
			<div class="col-md-2 control-label">
				@Html.LabelFor(model => model.ServerGroups)
				<span id="awsprofile-edit-remove-all-groups" class="glyphicon glyphicon-remove-sign pointer" title="Remove All Groups"></span>
			</div>
			<div class="col-md-10">
				<div id="awsprofile-edit-groups-wrapper"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input id="awsprofile-edit-submit" type="button" value="Save" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
	<style>
		.ui-autocomplete {
			height: 100px;
			overflow-x: hidden;
			overflow-y: auto;
		}

		.ui-menu .ui-menu-item {
			padding: 0 10px 0 0;
			white-space: nowrap;
		}
	</style>
	<script>
		$(document).ready(function() {
			var groups = @Html.Raw(Json.Encode(Model.ServerGroups));
			var selected = @Html.Raw(Json.Encode(Model.Groups));

			var groupsCtrl = new AutoCompleteMultiSelect();

			groupsCtrl.AttachmentId("#awsprofile-edit-groups-wrapper");
			groupsCtrl.List(groups);
			groupsCtrl.Load(selected);
			groupsCtrl.Setup();

			$("#awsprofile-edit-remove-all-groups").click(function(event) {
				groupsCtrl.RemoveAllLozenges();
			});

			$("#awsprofile-edit-submit").click(function(event) {
				groupsCtrl.ListToHiddenFields();
				$("#awsprofile-edit-form").submit();
			});
		});
	</script>
}

src/Interactive/WebPortal/Views/AwsProfile/Index.cshtml
@using Ica.StackIt.Interactive.WebPortal.Models
@model IEnumerable<Ica.StackIt.Interactive.WebPortal.Models.AwsProfileViewModel>

@{
	ViewBag.Title = "Index";
}

<div class="page-header">
	<a class="btn btn-primary pull-right" href="@Url.Action("Create")">
		<span class="glyphicon glyphicon-plus"></span>
		Add new AWS Profile
	</a>
	<h1>AWS Profiles</h1>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.AccessKeyId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.SecretAccessKey)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (AwsProfileViewModel item in Model)
		{
			<tr>
				<td>
					@Html.ActionLink(item.Name, "Details", new { id = item.Id }, new { title = "view details" })
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.AccessKeyId)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.SecretAccessKey)
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
					@Html.ActionLink("Details", "Details", new { id = item.Id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.Id })
				</td>
			</tr>
		}
	</tbody>
</table>