src/Interactive/WebPortal/Models/SessionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using Ica.StackIt.Core.Entities;
using System.ComponentModel;

namespace Ica.StackIt.Interactive.WebPortal.Models
{
	public class SessionViewModel
	{
		public List<AwsProfile> Profiles { get; set; }

		[DisplayName("Active AWS Profile")]
		public Guid SelectedProfileId { get; set; }
	}
}

src/Interactive/WebPortal/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using Ica.StackIt.Core.Entities;
using Ica.StackIt.Interactive.WebPortal.Models;

using Microsoft.Owin;

namespace Ica.StackIt.Interactive.WebPortal.Controllers
{
	public class SessionController : Controller
	{
		private readonly IOwinContext _owinContext;
		private readonly IUserProfileAccessManager _userProfileAccessManager;

		public SessionController(
			IOwinContext owinContext,
			IUserProfileAccessManager userProfileAccessManager)
		{
			_owinContext = owinContext;
			_userProfileAccessManager = userProfileAccessManager;
		}

		public ActionResult ProfileChooser()
		{
			string currentUsername = _owinContext.Authentication.User.Identity.Name;
			List<AwsProfile> profiles = _userProfileAccessManager.GetProfilesForUser(currentUsername).ToList();

			var model = new SessionViewModel
			{
				Profiles = profiles,
				SelectedProfileId = (Guid) Session[WebPortalConstants.ActiveProfileId]
			};

			return PartialView(model);
		}

		[HttpPost]
		public ActionResult SetActiveProfile(SessionViewModel model)
		{
			if (model.SelectedProfileId != default(Guid))
			{
				Session[WebPortalConstants.ActiveProfileId] = model.SelectedProfileId;
			}

			return RedirectToAction("Index", "Home");
		}
	}
}

src/Interactive/WebPortal/Views/Session/ProfileChooser.cshtml
@model Ica.StackIt.Interactive.WebPortal.Models.SessionViewModel

@{
	List<SelectListItem> profileSelectList = Model.Profiles.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
}

@using (Html.BeginForm("SetActiveProfile", "Session", FormMethod.Post, new { @id="ProfileChooser", @class="navbar-form" }))
{
	@Html.AntiForgeryToken()
		
	<div class="form-group">
		@Html.DisplayNameFor(x => Model.SelectedProfileId)
		@Html.DropDownListFor(model => Model.SelectedProfileId, profileSelectList, new
		{
			@id="ProfileChooserSelect",
			@class = "form-control"
		})
	</div>
}